version: '{build}'
clone_depth: 10
install:
    - ps: Install-Product node $Env:NODE_VERSION
    - node --version
    - npm --version
    - npm install
build: off
test_script:
    - npm run build
    - npm run coverage
after_test:
    - npm install -g codecov
    - .\node_modules\.bin\nyc report --reporter=text-lcov > coverage.lcov && codecov
deploy: off
notifications:
    - provider: Email
      on_build_status_changed: true
      on_build_success: false
      on_build_failure: false
